services:
  - type: web
    name: trading-smc-ict
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.10
    envVars:
      - key: FMP_API_KEY
        value: 1OFGTIDh9osWhsdERKSn6lL7Q9lUgeNH
